### ISSUE TITLE
JHOVE runner tool

### ISSUE THREAD

**Issue by moseshll** [mlibrary/rsvp#83]
This is done when a .rb/.sh pair runs the default JHOVE Perl script on a directory, with or without being translated by Postflight.

**Comment by huangjqq** [comment]
As an ingest auditor, I want to be able to see whether volumes pass JHOVE validation, so I can identify where remediation needs to take place.

Given a set of volumes to audit, when a list of filepaths is passed to the tool, then a list of whether each individual volume passed or failed validation and file containing errors will be generated.

**Whether each volume passed or failed**
MVP: output to the terminal of each filepath and pass or fail
Ideal: output to a file each filepath, whether a volume passed or failed, unique metadata fields that have errors for problem volumes

**Specific errors**
MVP: output to a text file the raw output of all errors
Ideal: output to a file
- object id
- metadata field producing error
- each unique error
- which files (with ranges, i.e. 1-5 instead of 1, 2, 3, 4, 5) within the object have that particular error

**Comment by moseshll** [comment]
Need not worry about shipment structure, this will target a directory of images (per CLI argument)
Output file can go to current directory.

**Comment by moseshll** [comment]
Explore an `-f` flag or shell trick for specifying multiple shipments in a file.

**Comment by huangjqq** [comment]
These are the listed errors for each of these volumes:

/n1/obj/a/t/d/atd7328.0054.001 | bad tiff resolution 200 dpi
/n1/obj/a/t/d/atd7328.0017.001 | jpeg 2000 size 2100x3500
/n1/obj/a/c/b/acb3910.0003.001 | 400 dpi TIFF 00000001.tif

**Comment by moseshll** [comment]
Need to check mis-parsed JHOVE output with /n1/obj/a/t/d/atd7328.0054.001

**Comment by huangjqq** [comment]
/n1/obj/1/4/5/1451867.0006.001 | Sequence skip between seq=00000706/page='646' and seq=00000711/page='

**Comment by moseshll** [comment]
Check for trailing newline in output file.

**Comment by moseshll** [comment]
It's suppressing a `detail` field iin the JHOVE output error message of the form `detail: 0 hits for context query: tiffMeta exactly one expected	field: JHOVE TIFF metadata`
Could append the "detail" field to the error description (under which files and optionally actual/expected values are listed). Right now we have `Invalid value for field: jhove tiff metadata` -- could make it `Invalid value for field: jhove tiff metadata (0 hits for context query: tiffmeta exactly one expected)`

**Comment by huangjqq** [comment]
/quod-prep/prep/d/dcu/huangjq/rsvp_testing/jhove_runner/jhove_20210909_110156_errors.txt

**Comment by moseshll** [comment]
Break out pagination and image resolution checks into modules that can be called from this app as well as stages.
Resolutions other than {bitonal: 600x600, contone: 400x400} will trigger an error.

**Comment by moseshll** [comment]
Output file should print out an "okay" line if no errors.

**Comment by moseshll** [comment]
It is not clear how to extract jp2 resolution. I'm not getting anything obviously useful from ImageMagick's `identify -verbose`
